//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        public int IdViaje { get; set; }
        public string origen { get; set; }
        public string destino { get; set; }
        public string distancia { get; set; }
        public System.DateTime horainicio { get; set; }
        public System.DateTime horafinal { get; set; }
        public string tarifa { get; set; }
        public Nullable<int> puntuacion { get; set; }
        public int IdCliente { get; set; }
        public int IdConductor { get; set; }
        public string estadoViaje { get; set; }
        public string comentarioCliente { get; set; }
    
        public virtual Conductor Conductor { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
